[package]
name = "ytui-ui"
version = "0.1.0"
edition = "2021"

[dependencies]
ratatui = { version = "*", features = ["macros", "unstable-widget-ref"]}
tokio = { workspace = true }
ytui-audio = { path = "../ytui-audio/" }
serde = { workspace = true }
smallvec = { workspace = true }
