[workspace]
resolver = "2"
members = [
  "ytui-invidious",
  "ytui-audio",
]

[workspace.dependencies]
serde = { version = "1", features = ["derive"] }
reqwest = { version = "0.12", features = ["stream"] }
tokio = { version = "1", features = ["full"] }
