[workspace]
members = [
    "front-end",
    "fetcher",
    "config",
]

[profile.release]
lto = true
panic = 'abort'
incremental = false
codegen-units = 8

[patch.crates-io]
libmpv = { path = "libmpv-rs/" }
